// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ariVQL1kypUjW0jL-W_WURrpXMn6Haw',
    appId: '1:112643227473:web:db525c316a7dd84fa8dd70',
    messagingSenderId: '112643227473',
    projectId: 'vlogify-prod',
    authDomain: 'vlogify-prod.firebaseapp.com',
    storageBucket: 'vlogify-prod.appspot.com',
    measurementId: 'G-9T954HTXC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARrXG-5M3ZDP2kT8x_z98sadjgibft8BE',
    appId: '1:112643227473:android:3635202e0efbed87a8dd70',
    messagingSenderId: '112643227473',
    projectId: 'vlogify-prod',
    storageBucket: 'vlogify-prod.appspot.com',
  );
}
